# Generated by Django 2.2 on 2020-05-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portaluser',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
