# Generated by Django 2.2 on 2020-05-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200514_1719'),
        ('hospital', '0006_examinationtype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/files/patient/%Y-%m-%d/')),
                ('details', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='users.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCheckupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_examined', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.TextField()),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_examiner', to='users.Examiner')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointment', to='hospital.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='users.Patient')),
                ('test_type', models.ManyToManyField(to='hospital.ExaminationType')),
            ],
        ),
    ]
