# Generated by Django 2.2 on 2020-05-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_finding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcheckupinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to='users.Patient'),
        ),
    ]
