# Generated by Django 2.2 on 2020-05-19 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200519_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcheckupinfo',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_examiner', to=settings.AUTH_USER_MODEL),
        ),
    ]
