# Generated by Django 2.2 on 2020-05-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200519_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('patient_checkup_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='patient.PatientCheckupInfo')),
            ],
        ),
    ]
