# Generated by Django 2.2 on 2020-05-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthistory',
            old_name='file',
            new_name='patient_file',
        ),
    ]
