# Generated by Django 2.2 on 2020-05-23 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20200523_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
