# Generated by Django 2.2 on 2020-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20200523_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
