# Generated by Django 2.2 on 2020-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_income_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
