# Generated by Django 2.2 on 2020-06-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_patienttransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienttransaction',
            old_name='user',
            new_name='Patient_trxn_user',
        ),
    ]
