# Generated by Django 2.2 on 2020-06-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20200609_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienttransaction',
            old_name='Patient_trxn_user',
            new_name='patient_trxn_user',
        ),
    ]
