# Generated by Django 2.2 on 2020-06-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20200609_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttransaction',
            name='lab_rate',
        ),
    ]
