# Generated by Django 2.2 on 2020-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_examinationtype_category'),
        ('patient', '0015_auto_20200609_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransaction',
            name='lab_rate',
            field=models.ManyToManyField(to='hospital.ExaminationType'),
        ),
        migrations.AlterField(
            model_name='patienttransaction',
            name='lab_item',
            field=models.ManyToManyField(related_name='lab_item', to='hospital.ExaminationType'),
        ),
    ]
