# Generated by Django 2.2 on 2020-06-09 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_examinationtype_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0016_auto_20200609_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middel_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('testdetails', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('examiner_finding', models.TextField()),
                ('doctor_recommendation', models.TextField()),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
                ('test', models.ManyToManyField(to='hospital.ExaminationType')),
            ],
        ),
    ]
