# Generated by Django 2.2 on 2020-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_patientinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttransaction',
            name='lab_rate',
        ),
        migrations.AddField(
            model_name='patienttransaction',
            name='lab_rate',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
