# Generated by Django 2.2 on 2020-06-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20200611_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='patient_trxn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='patient.PatientTransaction'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='middel_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
