# Generated by Django 2.2 on 2020-06-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20200612_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='patient_checkup_info',
        ),
    ]
