# Generated by Django 2.2 on 2020-06-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_remove_income_patient_checkup_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='patient_trxn',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='patient.PatientTransaction'),
            preserve_default=False,
        ),
    ]
