# Generated by Django 2.2 on 2020-06-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_auto_20200612_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttransaction',
            name='grandtotal',
        ),
        migrations.RemoveField(
            model_name='patienttransaction',
            name='lab_rate',
        ),
        migrations.RemoveField(
            model_name='patienttransaction',
            name='total',
        ),
        migrations.RemoveField(
            model_name='patienttransaction',
            name='vat',
        ),
    ]
