# Generated by Django 2.2 on 2020-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_auto_20200616_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransaction',
            name='grandtotal',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienttransaction',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienttransaction',
            name='vat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
