# Generated by Django 2.2 on 2020-06-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_auto_20200616_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttransaction',
            name='grandtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttransaction',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttransaction',
            name='vat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
