# Generated by Django 2.2 on 2020-05-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20200510_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalDoctor',
        ),
    ]
