# Generated by Django 2.2 on 2020-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_examinationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationtype',
            name='category',
            field=models.CharField(default='', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
