# Generated by Django 2.2 on 2020-05-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_examinationtype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationtype',
            name='category',
        ),
    ]
