# Generated by Django 2.2 on 2020-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_examinationtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationtype',
            name='cpt_code',
            field=models.IntegerField(default=89),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='reference_range',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='units',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
